### ISSUE TITLE
Where can I download vgg16bn_reducedfc.pth

### ISSUE THREAD

**Issue by hanjoo-cho** [SeanChenxy/TDRN#1]
Hello.

I have tried to reproduce your result.
However, I cannot find the way to download vgg16bn_reducedfc.pth.
Where can I get that file?

Thank you in advance.

**Comment by SeanChenxy** [comment]
Sorry for the late reply. All models are available at [GoogleDrive](https://drive.google.com/drive/folders/1_lgcOEOfdaiRCZrBIasYNGRjmH8YCFKF?usp=sharing) or [BaiduYun](https://pan.baidu.com/s/1I1FHecvQr8oVXe4kqvDxow)
